CREATE TABLE PUBACC_P2 (
    record_type TEXT,
    unique_system_identifier INTEGER NOT NULL,
    uls_file_number TEXT,
    ebf_number TEXT,
    callsign TEXT,
    lease_id TEXT,
    ls_site_link_id INTEGER,
    path_action_performed TEXT,
    path_number INTEGER,
    transmit_location_number INTEGER,
    transmit_antenna_number INTEGER,
    receiver_location_number INTEGER,
    receiver_antenna_number INTEGER,
    mas_dems_subtype TEXT,
    path_type_desc TEXT,
    passive_receiver_indicator TEXT,
    country_code TEXT,
    interference_to_gso TEXT,
    receiver_callsign TEXT,
    angular_sep REAL,
    cert_no_alternative TEXT,
    cert_no_interference TEXT,
    status_code TEXT,
    status_date TEXT
)