CREATE TABLE PUBACC_BD
(
    record_type TEXT NOT NULL,
    unique_system_identifier INTEGER NOT NULL,
    uls_file_number TEXT,
    ebf_number TEXT,
    involves_credit TEXT,
    involves_payment TEXT,
    involves_close_bidding TEXT,
    credits_paid TEXT,
    bc_same_elig_status TEXT,
    bc_diff_elig_status TEXT,
    bc_dnq_elig_status TEXT,
    payments TEXT,
    ip_same_elig_status TEXT,
    ip_diff_elig_status TEXT,
    ip_dnq_elig_status TEXT,
    closed_notification TEXT,
    qualifies_for_cb TEXT,
    dnq_for_cb TEXT,
    bc_ten_percent TEXT,
    bc_affiliate TEXT,
    bc_cont_elig TEXT,
    bc_shared TEXT,
    document TEXT,
    ip_ten_percent TEXT,
    ip_affiliate TEXT,
    ip_cont_elig TEXT,
    ip_shared TEXT,
    sec_date TEXT,
    lien_date TEXT,
    cb_ten_percent TEXT,
    cb_affiliate TEXT,
    cb_cont_elig TEXT,
    cb_shared TEXT,
    bidding_credit_type TEXT,
    bidding_credit_percent TEXT,
    bc_spectrum_capacity TEXT
)