CREATE TABLE PUBACC_A3
(
    record_type               TEXT,
    unique_system_identifier  INTEGER NOT NULL,
    uls_file_number           TEXT,
    ebf_number                TEXT,
    call_sign                 TEXT,
    lease_id                  TEXT,
    ls_site_link_id           INTEGER,
    antenna_action_performed  TEXT,
    antenna_number            INTEGER,
    location_number           INTEGER,
    receive_zone_code         TEXT,
    antenna_type_code         TEXT,
    height_to_tip             REAL,
    height_to_center_raat     REAL,
    antenna_make              TEXT,
    antenna_model             TEXT,
    tilt                      REAL,
    polarization_code         TEXT,
    beamwidth                 REAL,
    gain                      REAL,
    azimuth                   REAL,
    height_above_avg_terrain  REAL,
    diversity_height          REAL,
    diversity_gain            REAL,
    diversity_beam            REAL,
    reflector_height          REAL,
    reflector_width           REAL,
    reflector_separation      REAL,
    repeater_seq_num          INTEGER,
    back_to_back_tx_dish_gain REAL,
    back_to_back_rx_dish_gain REAL,
    location_name             TEXT,
    passive_repeater_id       INTEGER,
    alternative_cgsa_method   TEXT,
    path_number               INTEGER,
    line_loss                 REAL,
    status_code               TEXT,
    status_date               TEXT
)