CREATE TABLE PUBACC_AD (
    Record_Type TEXT,
    unique_system_identifier INTEGER NOT NULL,
    ULS_File_Number TEXT,
    EBF_Number TEXT,
    Application_Purpose TEXT,
    Application_Status TEXT,
    Application_Fee_Exempt TEXT,
    Regulatory_Fee_Exempt TEXT,
    Source TEXT,
    requested_expiration_date_mmdd TEXT,
    Receipt_Date TEXT,
    Notification_Code TEXT,
    Notification_date TEXT,
    Expanding_Area_or_Contour TEXT,
    Change_Type TEXT,
    Original_Application_Purpose TEXT,
    Requesting_A_Waiver TEXT,
    How_Many_Waivers_Requested INTEGER,
    Any_Attachments TEXT,
    Number_of_Requested_SIDs INTEGER,
    fee_control_num TEXT,
    date_entered TEXT,
    reason TEXT,
    frequency_coordination_indicat TEXT,
    emergency_sta TEXT,
    overall_change_type TEXT,
    slow_growth_ind TEXT,
    previous_waiver TEXT,
    waiver_deferral_fee TEXT,
    has_term_pending_ind TEXT,
    use_of_service TEXT
);