CREATE TABLE PUBACC_EN (
    record_type TEXT NOT NULL,
    unique_system_identifier INTEGER NOT NULL,
    uls_file_number TEXT,
    ebf_number TEXT,
    call_sign TEXT,
    entity_type TEXT,
    licensee_id TEXT,
    entity_name TEXT,
    first_name TEXT,
    mi TEXT,
    last_name TEXT,
    suffix TEXT,
    phone TEXT,
    fax TEXT,
    email TEXT,
    street_address TEXT,
    city TEXT,
    state TEXT,
    zip_code TEXT,
    po_box TEXT,
    attention_line TEXT,
    sgin TEXT,
    frn TEXT,
    applicant_type_code TEXT,
    applicant_type_other TEXT,
    status_code TEXT,
    status_date TEXT,
    lic_category_code TEXT,
    linked_license_id INTEGER,
    linked_callsign TEXT
);